import React, { useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";

function Login() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  const roomCode = searchParams.get("roomCode");

  const [showPassword, setShowPassword] = useState(false);

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  // =====================================================
  // (Anonymous ID is now generated by the backend)
  // =====================================================

  // =====================================================
  // LOGIN
  // =====================================================

  const handleSubmit = async (e) => {
    e.preventDefault();

    setError("");

    const cleanEmail = email.trim().toLowerCase();
    const cleanPassword = password;

    // ---------------------------------------------------
    // VALIDATION
    // ---------------------------------------------------

    if (!cleanEmail || !cleanPassword) {
      setError("Please enter your email and password.");
      return;
    }

    if (!roomCode) {
      setError(
        "Organization code is missing. Please join an organization first."
      );
      return;
    }

    try {
      setLoading(true);

      // =================================================
      // LOGIN API
      // =================================================

      const response = await fetch(
        "http://localhost:5000/api/auth/login",
        {
          method: "POST",

          headers: {
            "Content-Type": "application/json",
          },

          body: JSON.stringify({
            email: cleanEmail,
            password: cleanPassword,
            organizationCode: roomCode.trim().toUpperCase(),
          }),
        }
      );

      // =================================================
      // READ RESPONSE
      // =================================================

      const data = await response.json();

      // IMPORTANT:
      // Full login response ko console me mat print karo.
      // Isme email/name ya doosri private information ho sakti hai.

      // =================================================
      // BACKEND ERROR
      // =================================================

      if (!response.ok) {
        setError(data.message || "Login failed.");
        return;
      }

      // =================================================
      // VALIDATE USER
      // =================================================

      if (!data.user?.id) {
        setError("User information is missing.");
        return;
      }

      // =================================================
      // VALIDATE ORGANIZATION
      // =================================================

      if (!data.organization?.id) {
        setError("Organization information is missing.");
        return;
      }

      // =================================================
      // GET ROLE
      // =================================================

      const role = data.organization.role;

      // =================================================
      // GET APPROVAL STATUS
      // =================================================

      const approvalStatus = data.organization.approvalStatus;

      // =================================================
      // SESSION DATA
      // =================================================
      //
      // IMPORTANT:
      //
      // We never store complete user/organization objects.
      // Only the specific fields the UI actually needs are
      // written, each under its own key, so DashboardLayout,
      // AdminDashboard, and TopNavbar can read them directly
      // without any localStorage/sessionStorage or key-name
      // mismatch.
      //
      // =================================================

      sessionStorage.setItem("privatevoice_user_id", String(data.user.id));

      sessionStorage.setItem(
        "privatevoice_organization_id",
        String(data.organization.id)
      );

      sessionStorage.setItem("privatevoice_role", role);

      sessionStorage.setItem(
        "privatevoice_approval_status",
        approvalStatus
      );

      // Organization display fields — needed immediately by
      // DashboardLayout / AdminDashboard / TopNavbar after login,
      // not just after an admin action refreshes them later.

      if (data.organization.name) {
        sessionStorage.setItem(
          "privatevoice_organization_name",
          data.organization.name
        );
      } else {
        sessionStorage.removeItem("privatevoice_organization_name");
      }

      if (data.organization.code) {
        sessionStorage.setItem(
          "privatevoice_organization_code",
          data.organization.code
        );
      } else {
        sessionStorage.removeItem("privatevoice_organization_code");
      }

      if (data.organization.description) {
        sessionStorage.setItem(
          "privatevoice_organization_description",
          data.organization.description
        );
      } else {
        sessionStorage.removeItem(
          "privatevoice_organization_description"
        );
      }

      // =================================================
      // REAL IDENTITY — ADMIN ONLY
      // =================================================
      //
      // Full name is only ever stored for admins, and only so
      // the admin can see their own legitimate identity in
      // admin-facing UI (TopNavbar, AdminDashboard). Members
      // never have their real name written to storage — they
      // are identified solely by their session-scoped
      // anonymous ID. `role: "admin"` itself is unaffected;
      // this only controls what identity is displayed.
      //
      // =================================================

      if (role === "admin" && data.user.fullName) {
        sessionStorage.setItem(
          "privatevoice_full_name",
          data.user.fullName
        );
      } else {
        sessionStorage.removeItem("privatevoice_full_name");
      }

      // =================================================
      // JWT TOKEN & ANONYMOUS ID
      // =================================================

      if (data.token) {
        sessionStorage.setItem("privatevoice_token", data.token);
      }

      if (data.sessionAnonymousId) {
        sessionStorage.setItem("privatevoice_anonymous_id", data.sessionAnonymousId);
      }

      // Anonymous ID ko console me print nahi karna.

      // =================================================
      // ADMIN
      // =================================================

      if (role === "admin") {
        navigate("/anonymous-identity");
        return;
      }

      // =================================================
      // APPROVED MEMBER
      // =================================================

      if (role === "member" && approvalStatus === "approved") {
        navigate("/anonymous-identity");
        return;
      }

      // =================================================
      // PENDING MEMBER
      // =================================================

      if (role === "member" && approvalStatus === "pending") {
        setError(
          "Your request is still pending approval from the organization admin."
        );
        return;
      }

      // =================================================
      // REJECTED MEMBER
      // =================================================

      if (role === "member" && approvalStatus === "rejected") {
        setError(
          "Your request to join this organization was rejected."
        );
        return;
      }

      // =================================================
      // UNKNOWN STATUS
      // =================================================

      setError(
        "Your organization membership status could not be determined."
      );
    } catch (error) {
      // Real error object console me print karna avoid karo
      // production me, kyunki stack/details leak ho sakte hain.

      setError(
        "Unable to connect to server. Please make sure backend is running."
      );
    } finally {
      setLoading(false);
    }
  };

  // =====================================================
  // BACK
  // =====================================================

  const handleBack = () => {
    navigate(-1);
  };

  // =====================================================
  // REGISTER
  // =====================================================

  const handleRegister = () => {
    if (roomCode) {
      navigate(`/register?roomCode=${encodeURIComponent(roomCode)}`);
    } else {
      navigate("/register");
    }
  };

  // =====================================================
  // RENDER
  // =====================================================

  return (
    <main className="min-h-screen bg-[#F7F7F7] px-5 py-7 text-[#20252B] sm:px-8 lg:px-10">

      <div className="mx-auto flex min-h-[calc(100vh-56px)] w-full max-w-5xl flex-col">

        {/* BACK */}

        <div>
          <button
            type="button"
            onClick={handleBack}
            className="group flex items-center gap-2 border-0 bg-transparent px-0 py-2 text-sm font-semibold text-[#737C85] transition-all duration-200 hover:text-[#6F8580]"
          >
            <span className="text-lg transition-transform duration-200 group-hover:-translate-x-1">
              ←
            </span>

            <span>Back</span>
          </button>
        </div>

        {/* AUTH SECTION */}

        <section className="flex flex-1 items-center justify-center py-10">

          <div className="w-full max-w-md animate-[authIn_0.5s_ease-out]">

            {/* BRAND */}

            <div className="mb-7 text-center">

              <div className="mb-5 flex items-center justify-center gap-2.5">

                <span className="flex h-9 w-9 items-center justify-center gap-[2px] rounded-md bg-[#6F8580] shadow-sm">

                  <span className="h-[17px] w-[2px] rounded-full bg-white" />

                  <span className="h-3 w-[2px] rounded-full bg-white" />

                  <span className="h-[7px] w-[2px] rounded-full bg-white" />

                </span>

                <span className="text-sm font-bold tracking-[0.08em]">
                  PRIVATEVOICE
                </span>

              </div>

              <h1 className="text-3xl font-semibold tracking-[-0.04em] sm:text-[38px]">
                Welcome Back
              </h1>

              <p className="mt-3 text-sm leading-6 text-[#56606A]">
                Sign in to continue to your private communication space.
              </p>

              {/* ORGANIZATION CODE */}

              {roomCode && (
                <div className="mt-4 inline-flex items-center gap-2 border border-[#DDE3E1] bg-[#EEF2F1] px-3 py-2">

                  <span className="text-[10px] font-semibold uppercase tracking-wide text-[#8991A0]">
                    Organization
                  </span>

                  <span className="text-[11px] font-bold tracking-wide text-[#6F8580]">
                    {roomCode.toUpperCase()}
                  </span>

                </div>
              )}

            </div>

            {/* CARD */}

            <div className="border border-[#E5E7E6] bg-white p-6 shadow-[0_20px_50px_rgba(30,35,35,0.06)] sm:p-8">

              <form onSubmit={handleSubmit}>

                {/* EMAIL */}

                <div>

                  <label
                    htmlFor="login-email"
                    className="mb-2 block text-xs font-semibold"
                  >
                    Email address
                  </label>

                  <input
                    id="login-email"
                    type="email"
                    value={email}
                    onChange={(e) => {
                      setEmail(e.target.value);
                      setError("");
                    }}
                    placeholder="you@example.com"
                    autoComplete="email"
                    className="h-12 w-full border border-[#DADDDC] bg-white px-4 text-sm text-[#20252B] outline-none transition-all duration-200 placeholder:text-[#8991A0] focus:border-[#6F8580] focus:ring-4 focus:ring-[#6F8580]/10"
                  />

                </div>

                {/* PASSWORD */}

                <div className="mt-5">

                  <label
                    htmlFor="login-password"
                    className="mb-2 block text-xs font-semibold"
                  >
                    Password
                  </label>

                  <div className="relative">

                    <input
                      id="login-password"
                      type={showPassword ? "text" : "password"}
                      value={password}
                      onChange={(e) => {
                        setPassword(e.target.value);
                        setError("");
                      }}
                      placeholder="Enter your password"
                      autoComplete="current-password"
                      className="h-12 w-full border border-[#DADDDC] bg-white px-4 pr-16 text-sm text-[#20252B] outline-none transition-all duration-200 placeholder:text-[#8991A0] focus:border-[#6F8580] focus:ring-4 focus:ring-[#6F8580]/10"
                    />

                    <button
                      type="button"
                      onClick={() => setShowPassword((prev) => !prev)}
                      className="absolute right-3 top-1/2 -translate-y-1/2 border-0 bg-transparent px-2 py-1 text-[10px] font-semibold text-[#8991A0] transition-colors duration-200 hover:text-[#6F8580]"
                    >
                      {showPassword ? "Hide" : "Show"}
                    </button>

                  </div>

                </div>

                {/* ERROR */}

                {error && (
                  <div className="mt-4 border border-[#E5CFCF] bg-[#FBF5F5] px-3 py-2.5">

                    <p className="text-[11px] leading-5 text-[#9A5F5F]">
                      {error}
                    </p>

                  </div>
                )}

                {/* LOGIN BUTTON */}

                <button
                  type="submit"
                  disabled={loading}
                  className="group mt-6 flex h-12 w-full items-center justify-between bg-[#6F8580] px-5 text-xs font-semibold text-white transition-all duration-200 hover:-translate-y-0.5 hover:bg-[#5D716D] hover:shadow-lg disabled:cursor-not-allowed disabled:opacity-60"
                >

                  <span>
                    {loading ? "Logging in..." : "Login"}
                  </span>

                  <span className="text-lg transition-transform duration-200 group-hover:translate-x-1">
                    →
                  </span>

                </button>

              </form>

              {/* REGISTER */}

              <div className="mt-6 border-t border-[#E5E7E6] pt-5 text-center">

                <span className="text-[11px] text-[#8991A0]">
                  Don't have an account?
                </span>

                <button
                  type="button"
                  onClick={handleRegister}
                  className="ml-1 border-0 bg-transparent p-0 text-[11px] font-semibold text-[#6F8580] transition-colors duration-200 hover:text-[#5D716D]"
                >
                  Create Account
                </button>

              </div>

            </div>

            {/* PRIVACY */}

            <div className="mt-5 flex items-center justify-center gap-2 text-[9px] text-[#8991A0]">

              <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#6F8580]" />

              <span>
                Private by default
              </span>

              <span className="text-[#DADDDC]">
                /
              </span>

              <span>
                Secure communication
              </span>

            </div>

          </div>

        </section>

      </div>

      {/* ANIMATION */}

      <style>{`
        @keyframes authIn {
          from {
            opacity: 0;
            transform: translateY(18px) scale(0.985);
          }

          to {
            opacity: 1;
            transform: translateY(0) scale(1);
          }
        }
      `}</style>

    </main>
  );
}

export default Login;